/**
 * Append one event to the transactional outbox — the minimal ADR-0005 slice
 * (ADR-0026 point 10). Mirrors `appendAuditEvent`'s shape deliberately: same
 * "write inside the caller's transaction" contract, so a domain state
 * change, its audit event, and its outbox event either all commit or all
 * roll back together — the transactional-outbox guarantee
 * (`EVENT_CATALOGUE.md` §3, "Durability").
 *
 * `EventLogEntry.id` is the CloudEvents `id` (`EVENT_CATALOGUE.md` §1) and
 * the idempotency key every consumer keys on (§3) — generated by the
 * caller, not the database, so retrying the same logical publish (e.g. a
 * request retried after a timeout) can reuse the same id rather than
 * manufacturing a duplicate event.
 */

import { randomUUID } from 'node:crypto';

import type { PrismaService } from './prisma.service.js';

type PrismaTransaction = Parameters<Parameters<PrismaService['$transaction']>[0]>[0];

export interface OutboxEventInput {
  readonly id: string;
  readonly organisationId: string;
  readonly workspaceId?: string | null;
  readonly aggregateType: string;
  readonly aggregateId: string;
  /** `org.witness.<context>.<aggregate>.<past-tense-verb>.v<major>` (`EVENT_CATALOGUE.md` §2). */
  readonly eventType: string;
  readonly eventVersion?: number;
  readonly payload: Readonly<Record<string, unknown>>;
  readonly metadata?: Readonly<Record<string, unknown>>;
  readonly occurredAt: Date;
  readonly destination?: string;
}

export async function appendOutboxEvent(
  tx: PrismaTransaction,
  input: OutboxEventInput,
): Promise<void> {
  await tx.eventLogEntry.create({
    data: {
      id: input.id,
      organisationId: input.organisationId,
      workspaceId: input.workspaceId ?? null,
      aggregateType: input.aggregateType,
      aggregateId: input.aggregateId,
      eventType: input.eventType,
      eventVersion: input.eventVersion ?? 1,
      payload: input.payload as object,
      ...(input.metadata ? { metadata: input.metadata as object } : {}),
      occurredAt: input.occurredAt,
    },
  });

  await tx.outbox.create({
    data: {
      id: randomUUID(),
      eventId: input.id,
      destination: input.destination ?? 'graph-projector',
    },
  });
}
