// Witness ESLint configuration (flat config).
//
// The rules that matter here are the architectural ones. Style is Prettier's job
// and is not re-litigated in lint output — a lint run full of formatting noise is
// a lint run people stop reading.

import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/*.config.js',
      '**/*.config.mjs',
      // Generated by `next build`; Next.js owns its contents and regenerates it.
      '**/next-env.d.ts',
      'templates/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // `any` erases the type safety the strict tsconfig exists to provide.
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },
  {
    // ADR-0003: the domain layer imports nothing but the standard library and
    // other domain code. Enforced here as well as in CI, so a developer finds out
    // in their editor rather than in a pull request.
    files: ['packages/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'node:*',
                '@nestjs/*',
                '@prisma/*',
                'next',
                'react',
                'express',
                'zod',
                '@witness/config',
                '@witness/contracts',
              ],
              message:
                'The domain layer must import nothing but the standard library and other domain code (ADR-0003). Inject it as a port instead.',
            },
          ],
        },
      ],
    },
  },
  {
    // NestJS resolves constructor dependencies from `design:paramtypes` metadata,
    // which TypeScript only emits for VALUE imports. Rewriting an injected class
    // to `import type` erases the import and the metadata with it, so the rule's
    // autofix produces code that compiles cleanly and then fails at runtime with
    // an undefined dependency. Disabled here rather than worked around per file.
    files: ['services/**/*.ts'],
    rules: {
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
  {
    files: ['**/*.test.ts', '**/*.test.tsx', '**/prisma/seed.ts'],
    rules: {
      'no-restricted-imports': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
);
