/**
 * The native Keychain/Keystore-backed `CaptureSessionStore` adapter
 * (`@witness/participant-client`'s storage PORT — see that package's
 * `capture-session.ts` header comment for why a lost/stolen phone needs a
 * different threat model than a browser tab, which is what
 * `createLocalStorageCaptureSessionStore` in the same package is for).
 *
 * Backed by `@aparajita/capacitor-secure-storage` (v8, Capacitor 8):
 *
 * - **iOS**: the encrypted system Keychain, scoped to this app's bundle ID.
 *   Verified from the plugin's own documentation, not assumed — see
 *   `docs/mobile/SECURE_TOKEN_STORAGE.md` for the citation and the full
 *   threat-model writeup (including the one real asymmetry: iOS does not
 *   delete Keychain entries when the app itself is deleted).
 * - **Android**: `SharedPreferences` values encrypted with AES-256-GCM,
 *   using a key generated by and held in the Android Keystore. Deleted
 *   automatically on uninstall.
 * - **Web** (browser `vite dev` only — this app never ships as a hosted
 *   website): the plugin's own fallback is plain, unencrypted
 *   `localStorage`. `createSecureCaptureSessionStore` warns loudly rather
 *   than silently degrading, since that fallback provides none of this
 *   module's namesake security property.
 *
 * Never implements its own encryption — see the governing instruction's
 * "Do not implement custom cryptography." All cryptographic work happens
 * inside the OS-provided Keychain/Keystore, not in this file.
 */

import { SecureStorage } from '@aparajita/capacitor-secure-storage';
import { Capacitor } from '@capacitor/core';

import type { CaptureSession, CaptureSessionStore } from '@witness/participant-client';

const KEY_PREFIX = 'witness-capture-session:';

function isCaptureSession(value: unknown): value is CaptureSession {
  if (typeof value !== 'object' || value === null) return false;
  const record = value as Record<string, unknown>;
  return (
    typeof record['sessionId'] === 'string' &&
    typeof record['workspaceId'] === 'string' &&
    typeof record['participantId'] === 'string' &&
    typeof record['captureToken'] === 'string'
  );
}

export function createSecureCaptureSessionStore(): CaptureSessionStore {
  if (!Capacitor.isNativePlatform()) {
    console.warn(
      'createSecureCaptureSessionStore: running on a non-native platform (browser dev server). ' +
        'The capture token is being stored in plain, unencrypted localStorage via the secure-storage ' +
        "plugin's web fallback — this is fine for local development, but this code path never ships " +
        'in the native iOS/Android build.',
    );
  }

  return {
    async save(session: CaptureSession): Promise<void> {
      await SecureStorage.set(`${KEY_PREFIX}${session.sessionId}`, { ...session });
    },

    async load(sessionId: string): Promise<CaptureSession | null> {
      let data: unknown;
      try {
        data = await SecureStorage.get(`${KEY_PREFIX}${sessionId}`);
      } catch {
        return null;
      }
      if (!isCaptureSession(data)) return null;
      return data;
    },

    async clear(sessionId: string): Promise<void> {
      await SecureStorage.remove(`${KEY_PREFIX}${sessionId}`);
    },
  };
}
