#!/usr/bin/env bash
set -euo pipefail

# Prints the exact commands a human runs LOCALLY to create the Witness
# Participate Android release keystore. This script never creates the
# keystore itself, never touches a password, and is not meant to be piped
# into anything — a production signing key is a one-way decision (Play
# Store's Play App Signing still needs an upload key even when Google holds
# the final app signing key) that should be typed by the person who will
# own it, not generated by an agent on their behalf.
#
# After running the keytool command below, add the four secrets it produces
# to GitHub (Settings -> Secrets and variables -> Actions -> Secrets tab —
# these ARE genuinely secret, unlike the FIREBASE_* repository variables):
#   ANDROID_RELEASE_KEYSTORE_BASE64    (base64 of the .jks/.keystore file)
#   ANDROID_RELEASE_KEYSTORE_PASSWORD
#   ANDROID_RELEASE_KEY_ALIAS
#   ANDROID_RELEASE_KEY_PASSWORD
# .github/workflows/mobile-android-release-sign.yml already expects exactly
# these four names — nothing else to configure once they exist.

cat <<'EOF'
Step 1 — generate the keystore (run this yourself; do not paste the output
anywhere, including into this chat):

  keytool -genkeypair -v \
    -keystore witness-participate-release.jks \
    -alias witness-participate \
    -keyalg RSA -keysize 2048 -validity 10000

keytool will prompt for a keystore password, a key password (can match the
keystore password), and your name/organisation for the certificate — any
values are fine, this certificate is not publicly displayed. Keep
witness-participate-release.jks and both passwords somewhere durable
(a password manager, not this repository) — losing it means every future
release must ship under a new key, which the Play Store treats as a
different app.

Step 2 — base64-encode it for the GitHub secret:

  base64 -i witness-participate-release.jks | pbcopy   # macOS, copies to clipboard
  # or: base64 -w0 witness-participate-release.jks      # Linux, prints to stdout

Step 3 — add the four secrets (replace the placeholders yourself; do not
run these with real values inside a shared/logged session):

  gh secret set ANDROID_RELEASE_KEYSTORE_BASE64 --repo scigns/witness --body "<paste from step 2>"
  gh secret set ANDROID_RELEASE_KEYSTORE_PASSWORD --repo scigns/witness --body "<keystore password>"
  gh secret set ANDROID_RELEASE_KEY_ALIAS --repo scigns/witness --body "witness-participate"
  gh secret set ANDROID_RELEASE_KEY_PASSWORD --repo scigns/witness --body "<key password>"

Step 4 — dispatch the signing workflow:

  gh workflow run "Mobile — Android release signing" --repo scigns/witness --ref feat/mobile/witness-participate
EOF
